Updated the testing script to automatically run make

diff --git a/hwcCompile/run_tests b/hwcCompile/run_tests
--- a/hwcCompile/run_tests
+++ b/hwcCompile/run_tests
@@ -1,6 +1,16 @@
 #! /bin/bash
 
 
+make
+rc=$?
+
+if [[ $rc != 0 ]]
+then
+  echo "ERROR: make failed!" 1>&2
+  exit $rc
+fi
+
+
 if [[ $* == "" ]]
 then
   search=testcode/pass/
