Added the ability to specify a search path to run_tests

diff --git a/hwcCompile/run_tests b/hwcCompile/run_tests
--- a/hwcCompile/run_tests
+++ b/hwcCompile/run_tests
@@ -1,13 +1,21 @@
 #! /bin/bash
 
 
+if [[ $* == "" ]]
+then
+  search=testcode/
+else
+  search=$*
+fi
 
-attempt=0
+
+
+attempted=0
 passed=0
 
-for TESTCASE in $(find testcode -name *.debug.* | grep -v test_out | grep -v FAIL)
+for TESTCASE in $(find $search -name *.debug.* | grep -v test_out | grep -v FAIL)
 do
-  attempts=$((attempts+1))
+  attempted=$((attempted+1))
 
   phase=$(echo $TESTCASE | rev | cut -f1 -d'.' | rev)
   base=$(echo $TESTCASE | rev | cut -f3- -d'.' | rev)
@@ -41,13 +49,13 @@ do
 
   rm $base.debug.$phase.test_out
 
-  attempts=$((attempts+1))
+  passed=$((passed+1))
 done
 
 
-for TESTCASE in $(find testcode -name *.expect_fail | grep -v test_out | grep -v FAIL)
+for TESTCASE in $(find $search -name *.expect_fail | grep -v test_out | grep -v FAIL)
 do
-  attempts=$((attempts+1))
+  attempted=$((attempted+1))
 
   base=$(echo $TESTCASE | rev | cut -f2- -d'.' | rev)
 
@@ -80,7 +88,19 @@ do
 
   rm $base.expect_fail.*
 
-  attempts=$((attempts+1))
+  passed=$((passed+1))
 done
+
+
+
+if [[ $attempted = 0 ]]
+then
+  echo "ERROR: No testcases found!  Please check your search parameters!" 1>&2
+  echo "       Current Search: $search" 1>&2
+  exit 1
+fi
+
+echo
+echo "$0: Testing completed. $attempted testcases attempted, $passed passed, $((passed*100/attempted))%"
 
 
