Moved the simple_memory testcase into pass/, since it works in the simulator now

diff --git a/scripts/run_tests b/scripts/run_tests
--- a/scripts/run_tests
+++ b/scripts/run_tests
@@ -69,6 +69,7 @@ do
 done
 
 
+
 for TESTCASE in $(find $search -name *.expect_fail | grep -v test_out | grep -v FAIL)
 do
   attempted=$((attempted+1))
@@ -88,8 +89,8 @@ do
   if [[ $HWC_OUTPUT_SUFFIX != "" && -f $base.$HWC_OUTPUT_SUFFIX ]]
   then
     echo "Testcase $TESTCASE failed: the .$HWC_OUTPUT_SUFFIX file was created."
-    mv $base.debug.$phase.test_out $base.debug.$phase.FAIL
-    mv $base.$HWC_OUTPUT_SUFFIX    $base.debug.$phase.FAIL_$HWC_OUTPUT_SUFFIX
+    mv $base.expect_fail.test_out $base.expect_fail.FAIL
+    mv $base.$HWC_OUTPUT_SUFFIX   $base.expect_fail.FAIL_$HWC_OUTPUT_SUFFIX
     continue
   fi
 
@@ -103,6 +104,46 @@ do
   fi
 
   rm $base.expect_fail.*
+
+  passed=$((passed+1))
+done
+
+
+
+for TESTCASE in $(find $search -name *.stdout | grep -v test_out | grep -v FAIL)
+do
+  attempted=$((attempted+1))
+
+  base=$(echo $TESTCASE | rev | cut -f2- -d'.' | rev)
+
+  rm $base.stdout.* 2>/dev/null
+
+  {
+    ./$HWC_BIN < $base.$HWC_SUFFIX
+    rc=$?
+
+    echo
+    echo rc=$?
+  } > $base.stdout.test_out 2>&1
+
+  if [[ $HWC_OUTPUT_SUFFIX != "" && -f $base.$HWC_OUTPUT_SUFFIX ]]
+  then
+    echo "Testcase $TESTCASE failed: the .$HWC_OUTPUT_SUFFIX file was created."
+    mv $base.stdout.test_out    $base.stdout.FAIL
+    mv $base.$HWC_OUTPUT_SUFFIX $base.stdout.FAIL_$HWC_OUTPUT_SUFFIX
+    continue
+  fi
+
+  if [[ $(diff $base.stdout $base.stdout.test_out) != "" ]]
+  then
+    echo "Testcase $TESTCASE failed."
+      #diff $base.expect_fail $base.expect_fail.test_out 1>&2
+
+    mv $base.stdout.test_out $base.stdout.FAIL
+    continue
+  fi
+
+  rm $base.stdout.*
 
   passed=$((passed+1))
 done
